spring.application.name=example-app
server.port=8080

# Loggin
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %msg%n

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA and Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

# OpenAPI
springdoc.api-docs.path=/openapi.json
springdoc.swagger-ui.path=/

# springdoc.show-actuator=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
